// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://www.irs.gov/efile
package IRS3115

import (
	"encoding/xml"
)

// Element
type Irs3115 struct {
	XMLName xml.Name `xml:"IRS3115"`

	DocumentName string `xml:"documentName,attr"`

	ReferenceDocumentId string `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName string `xml:"referenceDocumentName,attr"`

	DocumentId IdType `xml:"documentId,attr"`

	SoftwareId SoftwareIdType `xml:"softwareId,attr"`

	SoftwareVersionNum SoftwareVersionType `xml:"softwareVersionNum,attr"`

	TaxYearBeginDt *DateType `xml:"TaxYearBeginDt"`

	TaxYearEndDt *DateType `xml:"TaxYearEndDt"`

	ContactPersonNm *PersonNameType `xml:"ContactPersonNm"`

	TelephoneNum *PhoneNumberType `xml:"TelephoneNum"`

	RcvChgMthdAcctLtrCorresFaxInd *BooleanType `xml:"RcvChgMthdAcctLtrCorresFaxInd"`

	IsMemberOfConsolidatedGroupInd *Irs3115IsMemberOfConsolidatedGroupInd `xml:"IsMemberOfConsolidatedGroupInd"`

	ApplicantAttachedFormInd *BooleanType `xml:"ApplicantAttachedFormInd"`

	WhoIsFilingForm *Irs3115WhoIsFilingForm `xml:"WhoIsFilingForm"`

	TypeOfAccountingMethod *Irs3115TypeOfAccountingMethod `xml:"TypeOfAccountingMethod"`

	DesignatedAccountingMthdChgNum []string `xml:"DesignatedAccountingMthdChgNum"`

	MethodOfAccountingOtherInd *Irs3115MethodOfAccountingOtherInd `xml:"MethodOfAccountingOtherInd"`

	RulesRstrAutoChangeProcInd *Irs3115RulesRstrAutoChangeProcInd `xml:"RulesRstrAutoChangeProcInd"`

	AllInformationProvidedInd *BooleanType `xml:"AllInformationProvidedInd"`

	ApplcntTrdBusReqChgRelatesInd *Irs3115ApplcntTrdBusReqChgRelatesInd `xml:"ApplcntTrdBusReqChgRelatesInd"`

	RequestChgUndSect1381Ind *BooleanType `xml:"RequestChgUndSect1381Ind"`

	PreparerOtherThanFilerNm *PersonNameType `xml:"PreparerOtherThanFilerNm"`

	AnyFederalReturnsUnderExamInd *BooleanType `xml:"AnyFederalReturnsUnderExamInd"`

	ReturnsUnderExaminationInfo []Irs3115ReturnsUnderExaminationInfo `xml:"ReturnsUnderExaminationInfo"`

	AcctMthdChgUndConsiderationInd *BooleanType `xml:"AcctMthdChgUndConsiderationInd"`

	AcctMthdChgUndConsiderationGrp []Irs3115AcctMthdChgUndConsiderationGrp `xml:"AcctMthdChgUndConsiderationGrp"`

	ExaminingAgentContactInfo []ContactAndTaxYearInfoType `xml:"ExaminingAgentContactInfo"`

	CopyProvidedToExaminingAgtInd *BooleanType `xml:"CopyProvidedToExaminingAgtInd"`

	AuditProtectionApplyYesInd *Irs3115AuditProtectionApplyYesInd `xml:"AuditProtectionApplyYesInd"`

	AuditProtectionApplyNoInd *Irs3115AuditProtectionApplyNoInd `xml:"AuditProtectionApplyNoInd"`

	NotUnderExamInd *CheckboxType `xml:"NotUnderExamInd"`

	ThreeMonthWindowInd *CheckboxType `xml:"ThreeMonthWindowInd"`

	OneHundredTwentyDaysPeriodInd *CheckboxType `xml:"OneHundredTwentyDaysPeriodInd"`

	ExaminationEndDt *DateType `xml:"ExaminationEndDt"`

	MethodNotBeforeDirectorInd *CheckboxType `xml:"MethodNotBeforeDirectorInd"`

	NegativeAdjustmentInd *CheckboxType `xml:"NegativeAdjustmentInd"`

	Capind *CheckboxType `xml:"CAPInd"`

	MemberJoinedGroupDt *DateType `xml:"MemberJoinedGroupDt"`

	AuditProtectionExamInd *CheckboxType `xml:"AuditProtectionExamInd"`

	OtherInd *CheckboxType `xml:"OtherInd"`

	FedReturnBeforeAppealsInd *BooleanType `xml:"FedReturnBeforeAppealsInd"`

	AcctMthdUnderCnsdrByFedCrtInd *Irs3115AcctMthdUnderCnsdrByFedCrtInd `xml:"AcctMthdUnderCnsdrByFedCrtInd"`

	AppealsOfficerInd *CheckboxType `xml:"AppealsOfficerInd"`

	CounselForTheGovernmentInd *CheckboxType `xml:"CounselForTheGovernmentInd"`

	AoorGovtCounselCntctInfo []ContactAndTaxYearInfoType `xml:"AOOrGovtCounselCntctInfo"`

	AoorGovtCounselProvCopyInd *BooleanType `xml:"AOOrGovtCounselProvCopyInd"`

	PrtshpScorpAcctMthdUndExamInd *BooleanType `xml:"PrtshpSCorpAcctMthdUndExamInd"`

	ChgInAcctMthdMadeInPast5YrsInd *Irs3115ChgInAcctMthdMadeInPast5YrsInd `xml:"ChgInAcctMthdMadeInPast5YrsInd"`

	PnReqPrvtLtrRlngTamAcctChgInd *Irs3115PnReqPrvtLtrRlngTamAcctChgInd `xml:"PnReqPrvtLtrRlngTamAcctChgInd"`

	RequestingChgToOverallAcctInd *BooleanType `xml:"RequestingChgToOverallAcctInd"`

	ProposedMethodUsedForBksInd *Irs3115ProposedMethodUsedForBksInd `xml:"ProposedMethodUsedForBksInd"`

	ConferenceOfRightRequestedInd *BooleanType `xml:"ConferenceOfRightRequestedInd"`

	GrossReceipts4YrsPreceding []GrossReceipts4YrsPrecedingType `xml:"GrossReceipts4YrsPreceding"`

	ChangeReqAllwUnderAutoChgInd *Irs3115ChangeReqAllwUnderAutoChgInd `xml:"ChangeReqAllwUnderAutoChgInd"`

	GroupMembersUsePrpsdMthdInd *Irs3115GroupMembersUsePrpsdMthdInd `xml:"GroupMembersUsePrpsdMthdInd"`

	QlfyRdcUserFeeRqrInfoAttInd *Irs3115QlfyRdcUserFeeRqrInfoAttInd `xml:"QlfyRdcUserFeeRqrInfoAttInd"`

	RequireUseCutOffBasisYesInd *Irs3115RequireUseCutOffBasisYesInd `xml:"RequireUseCutOffBasisYesInd"`

	RequireUseCutOffBasisNoInd *CheckboxType `xml:"RequireUseCutOffBasisNoInd"`

	NetSectionAdjustmentAmt *Irs3115NetSectionAdjustmentAmt `xml:"NetSectionAdjustmentAmt"`

	Sect481AAdjPrChgRqrInd *Irs3115Sect481AadjPrChgRqrInd `xml:"Sect481aAdjPrChgRqrInd"`

	TakingEntireSectAdjIntoAcctInd *BooleanType `xml:"TakingEntireSectAdjIntoAcctInd"`

	DeMinimisElection50Kind *CheckboxType `xml:"DeMinimisElection50KInd"`

	EligibleAcquisTransElectInd *CheckboxType `xml:"EligibleAcquisTransElectInd"`

	PartOfAdjAttrblBtwnMembersInd *Irs3115PartOfAdjAttrblBtwnMembersInd `xml:"PartOfAdjAttrblBtwnMembersInd"`

	Irs3115ScheduleA *Irs3115ScheduleAtype `xml:"IRS3115ScheduleA"`

	Irs3115ScheduleD *Irs3115ScheduleDtype `xml:"IRS3115ScheduleD"`

	Irs3115ScheduleE *Irs3115ScheduleEtype `xml:"IRS3115ScheduleE"`

	BusinessName []BusinessNameType `xml:"BusinessName"`

	PersonNm []PersonNameType `xml:"PersonNm"`

	Ssn []Ssntype `xml:"SSN"`

	Ein []Eintype `xml:"EIN"`

	MissingSsneinreasonCd string `xml:"MissingSSNEINReasonCd"`

	PrincipalBusinessActivityCd *BusinessActivityCodeType `xml:"PrincipalBusinessActivityCd"`

	InactivePrincipalBusActyCd string `xml:"InactivePrincipalBusActyCd"`

	PreparerFirmName *BusinessNameType `xml:"PreparerFirmName"`

	PreparerPersonNm *PersonNameType `xml:"PreparerPersonNm"`
}

// Element
type Irs3115IsMemberOfConsolidatedGroupInd struct {
	XMLName xml.Name `xml:"IsMemberOfConsolidatedGroupInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type WhoIsFilingFormExemptOrganizationInd struct {
	XMLName xml.Name `xml:"ExemptOrganizationInd"`

	CodeSectionTxt string `xml:"codeSectionTxt,attr"`

	Text string `xml:",chardata"`
}

// Element
type WhoIsFilingFormOtherApplicantTypeInd struct {
	XMLName xml.Name `xml:"OtherApplicantTypeInd"`

	Desc string `xml:"desc,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115WhoIsFilingForm struct {
	XMLName xml.Name `xml:"WhoIsFilingForm"`

	IndividualInd *CheckboxType `xml:"IndividualInd"`

	CorporationInd *CheckboxType `xml:"CorporationInd"`

	ControlledForeignCorpInd *CheckboxType `xml:"ControlledForeignCorpInd"`

	Corporation1050Ind *CheckboxType `xml:"Corporation1050Ind"`

	QualifiedPersonalSrvcCorpInd *CheckboxType `xml:"QualifiedPersonalSrvcCorpInd"`

	ExemptOrganizationInd *Irs3115WhoIsFilingFormWhoIsFilingFormExemptOrganizationInd `xml:"ExemptOrganizationInd"`

	CooperativeInd *CheckboxType `xml:"CooperativeInd"`

	PartnershipInd *CheckboxType `xml:"PartnershipInd"`

	ScorporationInd *CheckboxType `xml:"SCorporationInd"`

	InsuranceCompanySect816AInd *CheckboxType `xml:"InsuranceCompanySect816aInd"`

	InsuranceCompanySect831Ind *CheckboxType `xml:"InsuranceCompanySect831Ind"`

	OtherApplicantTypeInd *Irs3115WhoIsFilingFormWhoIsFilingFormOtherApplicantTypeInd `xml:"OtherApplicantTypeInd"`
}

// Element
type TypeOfAccountingMethodOtherApplicantTypeInd struct {
	XMLName xml.Name `xml:"OtherApplicantTypeInd"`

	Desc string `xml:"desc,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115TypeOfAccountingMethod struct {
	XMLName xml.Name `xml:"TypeOfAccountingMethod"`

	DepreciationOrAmortizationInd *CheckboxType `xml:"DepreciationOrAmortizationInd"`

	FinclProductsAndActivitiesInd *CheckboxType `xml:"FinclProductsAndActivitiesInd"`

	OtherApplicantTypeInd *Irs3115TypeOfAccountingMethodTypeOfAccountingMethodOtherApplicantTypeInd `xml:"OtherApplicantTypeInd"`
}

// Element
type Irs3115MethodOfAccountingOtherInd struct {
	XMLName xml.Name `xml:"MethodOfAccountingOtherInd"`

	MethodOfAccountingOtherDesc string `xml:"methodOfAccountingOtherDesc,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115RulesRstrAutoChangeProcInd struct {
	XMLName xml.Name `xml:"RulesRstrAutoChangeProcInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ApplcntTrdBusReqChgRelatesInd struct {
	XMLName xml.Name `xml:"ApplcntTrdBusReqChgRelatesInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ReturnsUnderExaminationInfo struct {
	XMLName xml.Name `xml:"ReturnsUnderExaminationInfo"`

	ExaminationPeriodBeginDt *DateType `xml:"ExaminationPeriodBeginDt"`

	ExaminationPeriodEndDt *DateType `xml:"ExaminationPeriodEndDt"`
}

// Element
type Irs3115AcctMthdChgUndConsiderationGrp struct {
	XMLName xml.Name `xml:"AcctMthdChgUndConsiderationGrp"`

	ConsiderationStartDt *DateType `xml:"ConsiderationStartDt"`

	ConsiderationEndDt *DateType `xml:"ConsiderationEndDt"`
}

// Element
type Irs3115AuditProtectionApplyYesInd struct {
	XMLName xml.Name `xml:"AuditProtectionApplyYesInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115AuditProtectionApplyNoInd struct {
	XMLName xml.Name `xml:"AuditProtectionApplyNoInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115AcctMthdUnderCnsdrByFedCrtInd struct {
	XMLName xml.Name `xml:"AcctMthdUnderCnsdrByFedCrtInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ChgInAcctMthdMadeInPast5YrsInd struct {
	XMLName xml.Name `xml:"ChgInAcctMthdMadeInPast5YrsInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115PnReqPrvtLtrRlngTamAcctChgInd struct {
	XMLName xml.Name `xml:"PnReqPrvtLtrRlngTamAcctChgInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ProposedMethodUsedForBksInd struct {
	XMLName xml.Name `xml:"ProposedMethodUsedForBksInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ChangeReqAllwUnderAutoChgInd struct {
	XMLName xml.Name `xml:"ChangeReqAllwUnderAutoChgInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115GroupMembersUsePrpsdMthdInd struct {
	XMLName xml.Name `xml:"GroupMembersUsePrpsdMthdInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115QlfyRdcUserFeeRqrInfoAttInd struct {
	XMLName xml.Name `xml:"QlfyRdcUserFeeRqrInfoAttInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115RequireUseCutOffBasisYesInd struct {
	XMLName xml.Name `xml:"RequireUseCutOffBasisYesInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115NetSectionAdjustmentAmt struct {
	XMLName xml.Name `xml:"NetSectionAdjustmentAmt"`

	IncreaseOrDecreaseCd string `xml:"increaseOrDecreaseCd,attr"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115Sect481AadjPrChgRqrInd struct {
	XMLName xml.Name `xml:"Sect481aAdjPrChgRqrInd"`

	Section481AAdjustmentAmt string `xml:"section481aAdjustmentAmt,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115PartOfAdjAttrblBtwnMembersInd struct {
	XMLName xml.Name `xml:"PartOfAdjAttrblBtwnMembersInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115IsMemberOfConsolidatedGroupInd struct {
	XMLName xml.Name `xml:"IsMemberOfConsolidatedGroupInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115WhoIsFilingFormWhoIsFilingFormExemptOrganizationInd struct {
	XMLName xml.Name `xml:"ExemptOrganizationInd"`

	CodeSectionTxt string `xml:"codeSectionTxt,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115WhoIsFilingFormWhoIsFilingFormOtherApplicantTypeInd struct {
	XMLName xml.Name `xml:"OtherApplicantTypeInd"`

	Desc string `xml:"desc,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115WhoIsFilingForm struct {
	XMLName xml.Name `xml:"WhoIsFilingForm"`

	IndividualInd *CheckboxType `xml:"IndividualInd"`

	CorporationInd *CheckboxType `xml:"CorporationInd"`

	ControlledForeignCorpInd *CheckboxType `xml:"ControlledForeignCorpInd"`

	Corporation1050Ind *CheckboxType `xml:"Corporation1050Ind"`

	QualifiedPersonalSrvcCorpInd *CheckboxType `xml:"QualifiedPersonalSrvcCorpInd"`

	ExemptOrganizationInd *Irs3115WhoIsFilingFormWhoIsFilingFormExemptOrganizationInd `xml:"ExemptOrganizationInd"`

	CooperativeInd *CheckboxType `xml:"CooperativeInd"`

	PartnershipInd *CheckboxType `xml:"PartnershipInd"`

	ScorporationInd *CheckboxType `xml:"SCorporationInd"`

	InsuranceCompanySect816AInd *CheckboxType `xml:"InsuranceCompanySect816aInd"`

	InsuranceCompanySect831Ind *CheckboxType `xml:"InsuranceCompanySect831Ind"`

	OtherApplicantTypeInd *Irs3115WhoIsFilingFormWhoIsFilingFormOtherApplicantTypeInd `xml:"OtherApplicantTypeInd"`
}

// Element
type Irs3115TypeOfAccountingMethodTypeOfAccountingMethodOtherApplicantTypeInd struct {
	XMLName xml.Name `xml:"OtherApplicantTypeInd"`

	Desc string `xml:"desc,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115TypeOfAccountingMethod struct {
	XMLName xml.Name `xml:"TypeOfAccountingMethod"`

	DepreciationOrAmortizationInd *CheckboxType `xml:"DepreciationOrAmortizationInd"`

	FinclProductsAndActivitiesInd *CheckboxType `xml:"FinclProductsAndActivitiesInd"`

	OtherApplicantTypeInd *Irs3115TypeOfAccountingMethodTypeOfAccountingMethodOtherApplicantTypeInd `xml:"OtherApplicantTypeInd"`
}

// Element
type Irs3115MethodOfAccountingOtherInd struct {
	XMLName xml.Name `xml:"MethodOfAccountingOtherInd"`

	MethodOfAccountingOtherDesc string `xml:"methodOfAccountingOtherDesc,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115RulesRstrAutoChangeProcInd struct {
	XMLName xml.Name `xml:"RulesRstrAutoChangeProcInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ApplcntTrdBusReqChgRelatesInd struct {
	XMLName xml.Name `xml:"ApplcntTrdBusReqChgRelatesInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ReturnsUnderExaminationInfo struct {
	XMLName xml.Name `xml:"ReturnsUnderExaminationInfo"`

	ExaminationPeriodBeginDt *DateType `xml:"ExaminationPeriodBeginDt"`

	ExaminationPeriodEndDt *DateType `xml:"ExaminationPeriodEndDt"`
}

// Element
type Irs3115AcctMthdChgUndConsiderationGrp struct {
	XMLName xml.Name `xml:"AcctMthdChgUndConsiderationGrp"`

	ConsiderationStartDt *DateType `xml:"ConsiderationStartDt"`

	ConsiderationEndDt *DateType `xml:"ConsiderationEndDt"`
}

// Element
type Irs3115AuditProtectionApplyYesInd struct {
	XMLName xml.Name `xml:"AuditProtectionApplyYesInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115AuditProtectionApplyNoInd struct {
	XMLName xml.Name `xml:"AuditProtectionApplyNoInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115AcctMthdUnderCnsdrByFedCrtInd struct {
	XMLName xml.Name `xml:"AcctMthdUnderCnsdrByFedCrtInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ChgInAcctMthdMadeInPast5YrsInd struct {
	XMLName xml.Name `xml:"ChgInAcctMthdMadeInPast5YrsInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115PnReqPrvtLtrRlngTamAcctChgInd struct {
	XMLName xml.Name `xml:"PnReqPrvtLtrRlngTamAcctChgInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ProposedMethodUsedForBksInd struct {
	XMLName xml.Name `xml:"ProposedMethodUsedForBksInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115ChangeReqAllwUnderAutoChgInd struct {
	XMLName xml.Name `xml:"ChangeReqAllwUnderAutoChgInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115GroupMembersUsePrpsdMthdInd struct {
	XMLName xml.Name `xml:"GroupMembersUsePrpsdMthdInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115QlfyRdcUserFeeRqrInfoAttInd struct {
	XMLName xml.Name `xml:"QlfyRdcUserFeeRqrInfoAttInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115RequireUseCutOffBasisYesInd struct {
	XMLName xml.Name `xml:"RequireUseCutOffBasisYesInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115NetSectionAdjustmentAmt struct {
	XMLName xml.Name `xml:"NetSectionAdjustmentAmt"`

	IncreaseOrDecreaseCd string `xml:"increaseOrDecreaseCd,attr"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115Sect481AadjPrChgRqrInd struct {
	XMLName xml.Name `xml:"Sect481aAdjPrChgRqrInd"`

	Section481AAdjustmentAmt string `xml:"section481aAdjustmentAmt,attr"`

	Text string `xml:",chardata"`
}

// Element
type Irs3115PartOfAdjAttrblBtwnMembersInd struct {
	XMLName xml.Name `xml:"PartOfAdjAttrblBtwnMembersInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type PresentMethodHybridInd struct {
	XMLName xml.Name `xml:"HybridInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type PresentMethod struct {
	XMLName xml.Name `xml:"PresentMethod"`

	CashInd *CheckboxType `xml:"CashInd"`

	AccrualInd *CheckboxType `xml:"AccrualInd"`

	HybridInd *PresentMethodHybridInd `xml:"HybridInd"`
}

// Element
type ProposedMethodHybridInd struct {
	XMLName xml.Name `xml:"HybridInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type ProposedMethod struct {
	XMLName xml.Name `xml:"ProposedMethod"`

	CashInd *CheckboxType `xml:"CashInd"`

	AccrualInd *CheckboxType `xml:"AccrualInd"`

	HybridInd *ProposedMethodHybridInd `xml:"HybridInd"`
}

// Element
type IncomeReceivedOrRptBfrEarnAmt struct {
	XMLName xml.Name `xml:"IncomeReceivedOrRptBfrEarnAmt"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type OtherAmt struct {
	XMLName xml.Name `xml:"OtherAmt"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type AllContractsQlfySectionExcInd struct {
	XMLName xml.Name `xml:"AllContractsQlfySectionExcInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type ApplcntReqExmptComplnMethodInd struct {
	XMLName xml.Name `xml:"ApplcntReqExmptComplnMethodInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type LtmfrContractsAsDefInSectInd struct {
	XMLName xml.Name `xml:"LTMfrContractsAsDefInSectInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type PresInvntryVltnMethodCmplncInd struct {
	XMLName xml.Name `xml:"PresInvntryVltnMethodCmplncInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type InventoryBeingChangedPresentMethodTxt struct {
	XMLName xml.Name `xml:"PresentMethodTxt"`

	Methods *InventoryIdentificationAndValuationMethodsType `xml:"Methods"`

	ValueEndOfTaxYearBefYrOfChgAmt *UsamountType `xml:"ValueEndOfTaxYearBefYrOfChgAmt"`
}

// Element
type InventoryBeingChangedProposedMethodTxt struct {
	XMLName xml.Name `xml:"ProposedMethodTxt"`

	Methods *InventoryIdentificationAndValuationMethodsType `xml:"Methods"`

	ValueEndOfTaxYearBefYrOfChgAmt *UsamountType `xml:"ValueEndOfTaxYearBefYrOfChgAmt"`
}

// Element
type InventoryBeingChanged struct {
	XMLName xml.Name `xml:"InventoryBeingChanged"`

	PresentMethodTxt *InventoryBeingChangedPresentMethodTxt `xml:"PresentMethodTxt"`

	ProposedMethodTxt *InventoryBeingChangedProposedMethodTxt `xml:"ProposedMethodTxt"`
}

// Element
type InventoryNotBeingChangedPresentMethodTxt struct {
	XMLName xml.Name `xml:"PresentMethodTxt"`

	Methods *InventoryIdentificationAndValuationMethodsType `xml:",any"`
}

// Element
type InventoryNotBeingChanged struct {
	XMLName xml.Name `xml:"InventoryNotBeingChanged"`

	PresentMethodTxt *InventoryNotBeingChangedPresentMethodTxt `xml:",any"`
}

// Element
type OtherCostsRqrToBeAllocated struct {
	XMLName xml.Name `xml:"OtherCostsRqrToBeAllocated"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	PresentMethodTxt *CheckOrNatype `xml:"PresentMethodTxt"`

	ProposedMethodTxt *CheckOrNatype `xml:"ProposedMethodTxt"`
}

// Element
type OtherCostsNotRqrToBeAllocated struct {
	XMLName xml.Name `xml:"OtherCostsNotRqrToBeAllocated"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	PresentMethodTxt *CheckOrNatype `xml:"PresentMethodTxt"`

	ProposedMethodTxt *CheckOrNatype `xml:"ProposedMethodTxt"`
}

// Element
type OtherIdentificationMethodInd struct {
	XMLName xml.Name `xml:"OtherIdentificationMethodInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type OtherValutionMethodInd struct {
	XMLName xml.Name `xml:"OtherValutionMethodInd"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	Text string `xml:",chardata"`
}

// Element
type ChangeInDeprecOrAmortization struct {
	XMLName xml.Name `xml:"ChangeInDeprecOrAmortization"`

	ReferenceDocumentId IdListType `xml:"referenceDocumentId,attr"`

	ReferenceDocumentName StringType `xml:"referenceDocumentName,attr"`

	PropertyDeprecUnderSectionInd *BooleanType `xml:"PropertyDeprecUnderSectionInd"`

	DepreciationOrAmortizationInd *BooleanType `xml:"DepreciationOrAmortizationInd"`

	ApplicableSectionTxt string `xml:"ApplicableSectionTxt"`

	DeprecOrAmortzElectionMadeInd *BooleanType `xml:"DeprecOrAmortzElectionMadeInd"`

	ElectionMadeTxt string `xml:"ElectionMadeTxt"`

	LivedInPropertyBefRentingItInd *BooleanType `xml:"LivedInPropertyBefRentingItInd"`

	PublicUtilityPropertyInd *BooleanType `xml:"PublicUtilityPropertyInd"`
}

// XSD ComplexType declarations

type UsitemizedEntryType struct {
	XMLName xml.Name

	Desc LineExplanationType `xml:"Desc"`

	Amt UsamountType `xml:"Amt"`
}

type ForeignItemizedEntryType struct {
	XMLName xml.Name

	Desc LineExplanationType `xml:"Desc"`

	ForeignAmt ForeignAmountType `xml:"ForeignAmt"`
}

type UsaddressType struct {
	XMLName xml.Name

	AddressLine1Txt StreetAddressType `xml:"AddressLine1Txt"`

	AddressLine2Txt *StreetAddressType `xml:"AddressLine2Txt"`

	CityNm CityType `xml:"CityNm"`

	StateAbbreviationCd StateType `xml:"StateAbbreviationCd"`

	Zipcd ZipcodeType `xml:"ZIPCd"`
}

type OtherUsaddressType struct {
	XMLName xml.Name

	AddressLine1Txt *StreetAddressType `xml:"AddressLine1Txt"`

	AddressLine2Txt *StreetAddressType `xml:"AddressLine2Txt"`

	CityNm *CityType `xml:"CityNm"`

	StateAbbreviationCd *StateType `xml:"StateAbbreviationCd"`

	Zipcd *ZipcodeType `xml:"ZIPCd"`
}

type ForeignAddressType struct {
	XMLName xml.Name

	AddressLine1Txt StreetAddressType `xml:"AddressLine1Txt"`

	AddressLine2Txt *StreetAddressType `xml:"AddressLine2Txt"`

	CityNm string `xml:"CityNm"`

	ProvinceOrStateNm string `xml:"ProvinceOrStateNm"`

	CountryCd CountryType `xml:"CountryCd"`

	ForeignPostalCd string `xml:"ForeignPostalCd"`
}

type OtherForeignAddressType struct {
	XMLName xml.Name

	AddressLine1Txt *StreetAddressType `xml:"AddressLine1Txt"`

	AddressLine2Txt *StreetAddressType `xml:"AddressLine2Txt"`

	CityNm string `xml:"CityNm"`

	ProvinceOrStateNm string `xml:"ProvinceOrStateNm"`

	CountryCd *CountryType `xml:"CountryCd"`

	ForeignPostalCd string `xml:"ForeignPostalCd"`
}

type BusinessNameType struct {
	XMLName xml.Name

	BusinessNameLine1Txt BusinessNameLine1Type `xml:"BusinessNameLine1Txt"`

	BusinessNameLine2Txt *BusinessNameLine2Type `xml:"BusinessNameLine2Txt"`
}

type NameAndAddressType struct {
	XMLName xml.Name

	PersonNm *PersonNameType `xml:"PersonNm"`

	BusinessName *BusinessNameType `xml:"BusinessName"`

	Usaddress *UsaddressType `xml:"USAddress"`

	ForeignAddress *ForeignAddressType `xml:"ForeignAddress"`
}

type PersonFullNameType struct {
	XMLName xml.Name

	PersonFirstNm PersonFirstNameType `xml:"PersonFirstNm"`

	PersonLastNm *PersonLastNameType `xml:"PersonLastNm"`
}

type IpaddressType struct {
	XMLName xml.Name

	Ipv4AddressTxt *Ipv4Type `xml:"IPv4AddressTxt"`

	Ipv6AddressTxt *Ipv6Type `xml:"IPv6AddressTxt"`
}

type VehicleDescriptionGrpType struct {
	XMLName xml.Name

	VehicleModelYr YearType `xml:"VehicleModelYr"`

	VehicleMakeNameTxt ShortDescriptionType `xml:"VehicleMakeNameTxt"`

	VehicleModelNameTxt ShortDescriptionType `xml:"VehicleModelNameTxt"`
}

type ForeignEntityIdentificationGrpType struct {
	XMLName xml.Name

	ForeignEntityReferenceIdNum string `xml:",any"`
}

type Form1099StateLocalTaxType struct {
	XMLName xml.Name

	StateAbbreviationCd StateType `xml:"StateAbbreviationCd"`

	StateIdNum string `xml:"StateIdNum"`

	StateTaxWithheldAmt UsamountNntype `xml:"StateTaxWithheldAmt"`

	LocalAbbreviationCdTxt string `xml:"LocalAbbreviationCdTxt"`

	LocalityNm *ShortDescriptionType `xml:"LocalityNm"`

	LocalTaxWithheldAmt *UsamountNntype `xml:"LocalTaxWithheldAmt"`
}

type Form1099OtherStateLocalTaxType struct {
	XMLName xml.Name

	StateTaxWithheldAmt UsamountNntype `xml:"StateTaxWithheldAmt"`

	StateAbbreviationCd StateType `xml:"StateAbbreviationCd"`

	StateIdNum string `xml:"StateIdNum"`

	StateIncomeAmt *UsamountNntype `xml:"StateIncomeAmt"`

	LocalTaxWithheldAmt *UsamountNntype `xml:"LocalTaxWithheldAmt"`

	LocalityNm *ShortDescriptionType `xml:"LocalityNm"`

	LocalIncomeAmt *UsamountNntype `xml:"LocalIncomeAmt"`
}

type Irs3115Type struct {
	XMLName xml.Name

	TaxYearBeginDt *DateType `xml:"TaxYearBeginDt"`

	TaxYearEndDt *DateType `xml:"TaxYearEndDt"`

	ContactPersonNm *PersonNameType `xml:"ContactPersonNm"`

	TelephoneNum *PhoneNumberType `xml:"TelephoneNum"`

	RcvChgMthdAcctLtrCorresFaxInd *BooleanType `xml:"RcvChgMthdAcctLtrCorresFaxInd"`

	IsMemberOfConsolidatedGroupInd *Irs3115IsMemberOfConsolidatedGroupInd `xml:"IsMemberOfConsolidatedGroupInd"`

	ApplicantAttachedFormInd *BooleanType `xml:"ApplicantAttachedFormInd"`

	WhoIsFilingForm *Irs3115WhoIsFilingForm `xml:"WhoIsFilingForm"`

	TypeOfAccountingMethod *Irs3115TypeOfAccountingMethod `xml:"TypeOfAccountingMethod"`

	DesignatedAccountingMthdChgNum []string `xml:"DesignatedAccountingMthdChgNum"`

	MethodOfAccountingOtherInd *Irs3115MethodOfAccountingOtherInd `xml:"MethodOfAccountingOtherInd"`

	RulesRstrAutoChangeProcInd *Irs3115RulesRstrAutoChangeProcInd `xml:"RulesRstrAutoChangeProcInd"`

	AllInformationProvidedInd *BooleanType `xml:"AllInformationProvidedInd"`

	ApplcntTrdBusReqChgRelatesInd *Irs3115ApplcntTrdBusReqChgRelatesInd `xml:"ApplcntTrdBusReqChgRelatesInd"`

	RequestChgUndSect1381Ind *BooleanType `xml:"RequestChgUndSect1381Ind"`

	PreparerOtherThanFilerNm *PersonNameType `xml:"PreparerOtherThanFilerNm"`

	AnyFederalReturnsUnderExamInd *BooleanType `xml:"AnyFederalReturnsUnderExamInd"`

	ReturnsUnderExaminationInfo []Irs3115ReturnsUnderExaminationInfo `xml:"ReturnsUnderExaminationInfo"`

	AcctMthdChgUndConsiderationInd *BooleanType `xml:"AcctMthdChgUndConsiderationInd"`

	AcctMthdChgUndConsiderationGrp []Irs3115AcctMthdChgUndConsiderationGrp `xml:"AcctMthdChgUndConsiderationGrp"`

	ExaminingAgentContactInfo []ContactAndTaxYearInfoType `xml:"ExaminingAgentContactInfo"`

	CopyProvidedToExaminingAgtInd *BooleanType `xml:"CopyProvidedToExaminingAgtInd"`

	AuditProtectionApplyYesInd *Irs3115AuditProtectionApplyYesInd `xml:"AuditProtectionApplyYesInd"`

	AuditProtectionApplyNoInd *Irs3115AuditProtectionApplyNoInd `xml:"AuditProtectionApplyNoInd"`

	NotUnderExamInd *CheckboxType `xml:"NotUnderExamInd"`

	ThreeMonthWindowInd *CheckboxType `xml:"ThreeMonthWindowInd"`

	OneHundredTwentyDaysPeriodInd *CheckboxType `xml:"OneHundredTwentyDaysPeriodInd"`

	ExaminationEndDt *DateType `xml:"ExaminationEndDt"`

	MethodNotBeforeDirectorInd *CheckboxType `xml:"MethodNotBeforeDirectorInd"`

	NegativeAdjustmentInd *CheckboxType `xml:"NegativeAdjustmentInd"`

	Capind *CheckboxType `xml:"CAPInd"`

	MemberJoinedGroupDt *DateType `xml:"MemberJoinedGroupDt"`

	AuditProtectionExamInd *CheckboxType `xml:"AuditProtectionExamInd"`

	OtherInd *CheckboxType `xml:"OtherInd"`

	FedReturnBeforeAppealsInd *BooleanType `xml:"FedReturnBeforeAppealsInd"`

	AcctMthdUnderCnsdrByFedCrtInd *Irs3115AcctMthdUnderCnsdrByFedCrtInd `xml:"AcctMthdUnderCnsdrByFedCrtInd"`

	AppealsOfficerInd *CheckboxType `xml:"AppealsOfficerInd"`

	CounselForTheGovernmentInd *CheckboxType `xml:"CounselForTheGovernmentInd"`

	AoorGovtCounselCntctInfo []ContactAndTaxYearInfoType `xml:"AOOrGovtCounselCntctInfo"`

	AoorGovtCounselProvCopyInd *BooleanType `xml:"AOOrGovtCounselProvCopyInd"`

	PrtshpScorpAcctMthdUndExamInd *BooleanType `xml:"PrtshpSCorpAcctMthdUndExamInd"`

	ChgInAcctMthdMadeInPast5YrsInd *Irs3115ChgInAcctMthdMadeInPast5YrsInd `xml:"ChgInAcctMthdMadeInPast5YrsInd"`

	PnReqPrvtLtrRlngTamAcctChgInd *Irs3115PnReqPrvtLtrRlngTamAcctChgInd `xml:"PnReqPrvtLtrRlngTamAcctChgInd"`

	RequestingChgToOverallAcctInd *BooleanType `xml:"RequestingChgToOverallAcctInd"`

	ProposedMethodUsedForBksInd *Irs3115ProposedMethodUsedForBksInd `xml:"ProposedMethodUsedForBksInd"`

	ConferenceOfRightRequestedInd *BooleanType `xml:"ConferenceOfRightRequestedInd"`

	GrossReceipts4YrsPreceding []GrossReceipts4YrsPrecedingType `xml:"GrossReceipts4YrsPreceding"`

	ChangeReqAllwUnderAutoChgInd *Irs3115ChangeReqAllwUnderAutoChgInd `xml:"ChangeReqAllwUnderAutoChgInd"`

	GroupMembersUsePrpsdMthdInd *Irs3115GroupMembersUsePrpsdMthdInd `xml:"GroupMembersUsePrpsdMthdInd"`

	QlfyRdcUserFeeRqrInfoAttInd *Irs3115QlfyRdcUserFeeRqrInfoAttInd `xml:"QlfyRdcUserFeeRqrInfoAttInd"`

	RequireUseCutOffBasisYesInd *Irs3115RequireUseCutOffBasisYesInd `xml:"RequireUseCutOffBasisYesInd"`

	RequireUseCutOffBasisNoInd *CheckboxType `xml:"RequireUseCutOffBasisNoInd"`

	NetSectionAdjustmentAmt *Irs3115NetSectionAdjustmentAmt `xml:"NetSectionAdjustmentAmt"`

	Sect481AAdjPrChgRqrInd *Irs3115Sect481AadjPrChgRqrInd `xml:"Sect481aAdjPrChgRqrInd"`

	TakingEntireSectAdjIntoAcctInd *BooleanType `xml:"TakingEntireSectAdjIntoAcctInd"`

	DeMinimisElection50Kind *CheckboxType `xml:"DeMinimisElection50KInd"`

	EligibleAcquisTransElectInd *CheckboxType `xml:"EligibleAcquisTransElectInd"`

	PartOfAdjAttrblBtwnMembersInd *Irs3115PartOfAdjAttrblBtwnMembersInd `xml:"PartOfAdjAttrblBtwnMembersInd"`

	Irs3115ScheduleA *Irs3115ScheduleAtype `xml:"IRS3115ScheduleA"`

	Irs3115ScheduleD *Irs3115ScheduleDtype `xml:"IRS3115ScheduleD"`

	Irs3115ScheduleE *Irs3115ScheduleEtype `xml:"IRS3115ScheduleE"`

	BusinessName []BusinessNameType `xml:"BusinessName"`

	PersonNm []PersonNameType `xml:"PersonNm"`

	Ssn []Ssntype `xml:"SSN"`

	Ein []Eintype `xml:"EIN"`

	MissingSsneinreasonCd string `xml:"MissingSSNEINReasonCd"`

	PrincipalBusinessActivityCd *BusinessActivityCodeType `xml:"PrincipalBusinessActivityCd"`

	InactivePrincipalBusActyCd string `xml:"InactivePrincipalBusActyCd"`

	PreparerFirmName *BusinessNameType `xml:"PreparerFirmName"`

	PreparerPersonNm *PersonNameType `xml:"PreparerPersonNm"`
}

type GrossReceipts4YrsPrecedingType struct {
	XMLName xml.Name

	GrossReceiptsForFirstPrecYrAmt *UsamountType `xml:"GrossReceiptsForFirstPrecYrAmt"`

	FirstPrecedingYearEndDt *YearMonthType `xml:"FirstPrecedingYearEndDt"`

	GrossReceiptsFor2NdPrecYrAmt *UsamountType `xml:"GrossReceiptsFor2ndPrecYrAmt"`

	SecondPrecedingYearEndDt *YearMonthType `xml:"SecondPrecedingYearEndDt"`

	GrossReceiptsForThirdPrecYrAmt *UsamountType `xml:"GrossReceiptsForThirdPrecYrAmt"`

	ThirdPrecedingYearEndDt *YearMonthType `xml:"ThirdPrecedingYearEndDt"`

	GrossReceiptsFor4ThPrecYrAmt *UsamountType `xml:"GrossReceiptsFor4thPrecYrAmt"`

	FourthPrecedingYearEndDt *YearMonthType `xml:"FourthPrecedingYearEndDt"`
}

type Irs3115ScheduleAtype struct {
	XMLName xml.Name

	PresentMethod *PresentMethod `xml:"PresentMethod"`

	ProposedMethod *ProposedMethod `xml:"ProposedMethod"`

	RequestingRecurItemExcInd *BooleanType `xml:"RequestingRecurItemExcInd"`

	CashOrAccrualMethodChangeInd BooleanType `xml:"CashOrAccrualMethodChangeInd"`

	IncomeAccruedButNotReceivedAmt *UsamountType `xml:"IncomeAccruedButNotReceivedAmt"`

	IncomeAccruedButNotRcvdNonecd string `xml:"IncomeAccruedButNotRcvdNONECd"`

	IncomeReceivedOrRptBfrEarnAmt *IncomeReceivedOrRptBfrEarnAmt `xml:"IncomeReceivedOrRptBfrEarnAmt"`

	IncomeRcvdOrRptBefEarnNonecd string `xml:"IncomeRcvdOrRptBefEarnNONECd"`

	ExpensesAccruedButNotPaidAmt *UsamountType `xml:"ExpensesAccruedButNotPaidAmt"`

	ExpensesAccruedButNotPdNonecd string `xml:"ExpensesAccruedButNotPdNONECd"`

	PrepaidExpensePrevDeductedAmt *UsamountType `xml:"PrepaidExpensePrevDeductedAmt"`

	PrepaidExpnsPrevDedNonecd string `xml:"PrepaidExpnsPrevDedNONECd"`

	SuppliesOnHandPrevDeductedAmt *UsamountType `xml:"SuppliesOnHandPrevDeductedAmt"`

	SupOnHandPrevDeductedNonecd string `xml:"SupOnHandPrevDeductedNONECd"`

	InventoryOnHandPrevDeductedAmt *UsamountType `xml:"InventoryOnHandPrevDeductedAmt"`

	InvntryOnHandPrevDedNonecd string `xml:"InvntryOnHandPrevDedNONECd"`

	OtherAmt *OtherAmt `xml:"OtherAmt"`

	OtherAmountNonecd string `xml:"OtherAmountNONECd"`

	NetSectionAdjustmentAmt *UsamountType `xml:"NetSectionAdjustmentAmt"`

	NetSectionAdjustmentNoneCd string `xml:"NetSectionAdjustmentNoneCd"`
}

type Irs3115ScheduleDtype struct {
	XMLName xml.Name

	LongTermApplicantContractsInd *BooleanType `xml:"LongTermApplicantContractsInd"`

	AllContractsQlfySectionExcInd *AllContractsQlfySectionExcInd `xml:"AllContractsQlfySectionExcInd"`

	ApplcntReqPctOfCompMethodInd *BooleanType `xml:"ApplcntReqPctOfCompMethodInd"`

	CmplnFctrCstCstSmplfdMthdInd *BooleanType `xml:"CmplnFctrCstCstSmplfdMthdInd"`

	ApplcntReqExmptComplnMethodInd *ApplcntReqExmptComplnMethodInd `xml:"ApplcntReqExmptComplnMethodInd"`

	LtmfrContractsAsDefInSectInd *LtmfrContractsAsDefInSectInd `xml:"LTMfrContractsAsDefInSectInd"`

	EnterCostPlusLtcntrctInd *BooleanType `xml:"EnterCostPlusLTCntrctInd"`

	EnterFederalLtcntrctInd *BooleanType `xml:"EnterFederalLTCntrctInd"`

	ApplicationSubjectToSectionInd *BooleanType `xml:"ApplicationSubjectToSectionInd"`

	PresInvntryVltnMethodCmplncInd *PresInvntryVltnMethodCmplncInd `xml:"PresInvntryVltnMethodCmplncInd"`

	InventoryBeingChanged *InventoryBeingChanged `xml:"InventoryBeingChanged"`

	InventoryNotBeingChanged *InventoryNotBeingChanged `xml:"InventoryNotBeingChanged"`

	CostOffsetMethodInd *BooleanType `xml:"CostOffsetMethodInd"`

	DirectMaterial *PresentAndProposedMethodCheckboxesType `xml:"DirectMaterial"`

	DirectLabor *PresentAndProposedMethodCheckboxesType `xml:"DirectLabor"`

	IndirectLabor *PresentAndProposedMethodCheckboxesType `xml:"IndirectLabor"`

	OfficersCompensation *PresentAndProposedMethodCheckboxesType `xml:"OfficersCompensation"`

	PensionAndOtherRelatedCosts *PresentAndProposedMethodCheckboxesType `xml:"PensionAndOtherRelatedCosts"`

	EmployeeBenefits *PresentAndProposedMethodCheckboxesType `xml:"EmployeeBenefits"`

	IndirectMaterialsAndSupplies *PresentAndProposedMethodCheckboxesType `xml:"IndirectMaterialsAndSupplies"`

	PurchasingCosts *PresentAndProposedMethodCheckboxesType `xml:"PurchasingCosts"`

	HandlingProcessingAssemblyCost *PresentAndProposedMethodCheckboxesType `xml:"HandlingProcessingAssemblyCost"`

	OffsiteStorageWarehousingCosts *PresentAndProposedMethodCheckboxesType `xml:"OffsiteStorageWarehousingCosts"`

	DeprecAmortzAndCostRecovery *PresentAndProposedMethodCheckboxesType `xml:"DeprecAmortzAndCostRecovery"`

	Depletion *PresentAndProposedMethodCheckboxesType `xml:"Depletion"`

	Rent *PresentAndProposedMethodCheckboxesType `xml:"Rent"`

	TaxesNotStateLocalAndForeign *PresentAndProposedMethodCheckboxesType `xml:"TaxesNotStateLocalAndForeign"`

	Insurance *PresentAndProposedMethodCheckboxesType `xml:"Insurance"`

	Utilities *PresentAndProposedMethodCheckboxesType `xml:"Utilities"`

	MaintRepairsProdResaleLtcntrct *PresentAndProposedMethodCheckboxesType `xml:"MaintRepairsProdResaleLTCntrct"`

	EngineeringAndDesignCosts *PresentAndProposedMethodCheckboxesType `xml:"EngineeringAndDesignCosts"`

	ReworkLaborScrapAndSpoilage *PresentAndProposedMethodCheckboxesType `xml:"ReworkLaborScrapAndSpoilage"`

	ToolsAndEquipment *PresentAndProposedMethodCheckboxesType `xml:"ToolsAndEquipment"`

	QualityControlAndInspection *PresentAndProposedMethodCheckboxesType `xml:"QualityControlAndInspection"`

	ContractBiddingExpnssIncurred *PresentAndProposedMethodCheckboxesType `xml:"ContractBiddingExpnssIncurred"`

	LicensingAndFranchiseCosts *PresentAndProposedMethodCheckboxesType `xml:"LicensingAndFranchiseCosts"`

	CapitalizableServiceCosts *PresentAndProposedMethodCheckboxesType `xml:"CapitalizableServiceCosts"`

	AdministrativeCosts *PresentAndProposedMethodCheckboxesType `xml:"AdministrativeCosts"`

	RsrchAndExptlExpnssLtcontracts *PresentAndProposedMethodCheckboxesType `xml:"RsrchAndExptlExpnssLTContracts"`

	Interest *PresentAndProposedMethodCheckboxesType `xml:"Interest"`

	OtherCostsRqrToBeAllocated *OtherCostsRqrToBeAllocated `xml:"OtherCostsRqrToBeAllocated"`

	MarketingSellAdvtgDistriExpnss *PresentAndProposedMethodCheckboxesType `xml:"MarketingSellAdvtgDistriExpnss"`

	OtherResearchAndExptlExpenses *PresentAndProposedMethodCheckboxesType `xml:"OtherResearchAndExptlExpenses"`

	OtherBiddingExpenses *PresentAndProposedMethodCheckboxesType `xml:"OtherBiddingExpenses"`

	GeneralAndAdministrativeCosts *PresentAndProposedMethodCheckboxesType `xml:"GeneralAndAdministrativeCosts"`

	IncomeTaxes *PresentAndProposedMethodCheckboxesType `xml:"IncomeTaxes"`

	CostOfStrikes *PresentAndProposedMethodCheckboxesType `xml:"CostOfStrikes"`

	WarrantyProductLiabilityCosts *PresentAndProposedMethodCheckboxesType `xml:"WarrantyProductLiabilityCosts"`

	Section179Costs *PresentAndProposedMethodCheckboxesType `xml:"Section179Costs"`

	OnSiteStorage *PresentAndProposedMethodCheckboxesType `xml:"OnSiteStorage"`

	OtherDeprecAmortzCostRecovery *PresentAndProposedMethodCheckboxesType `xml:"OtherDeprecAmortzCostRecovery"`

	OtherCostsNotRqrToBeAllocated *OtherCostsNotRqrToBeAllocated `xml:"OtherCostsNotRqrToBeAllocated"`
}

type InventoryIdentificationAndValuationMethodsType struct {
	XMLName xml.Name

	SpecificIdentificationInd *CheckboxType `xml:"SpecificIdentificationInd"`

	Fifoind *CheckboxType `xml:"FIFOInd"`

	Lifoind *CheckboxType `xml:"LIFOInd"`

	OtherIdentificationMethodInd *OtherIdentificationMethodInd `xml:"OtherIdentificationMethodInd"`

	CostInd *CheckboxType `xml:"CostInd"`

	CostOrMarketInd *CheckboxType `xml:"CostOrMarketInd"`

	RetailCostInd *CheckboxType `xml:"RetailCostInd"`

	LowerRetailOfCostOrMarketInd *CheckboxType `xml:"LowerRetailOfCostOrMarketInd"`

	OtherValutionMethodInd *OtherValutionMethodInd `xml:"OtherValutionMethodInd"`
}

type PresentAndProposedMethodCheckboxesType struct {
	XMLName xml.Name

	PresentMethodTxt *CheckOrNatype `xml:"PresentMethodTxt"`

	ProposedMethodTxt *CheckOrNatype `xml:"ProposedMethodTxt"`
}

type Irs3115ScheduleEtype struct {
	XMLName xml.Name

	ChangeInDeprecOrAmortization []ChangeInDeprecOrAmortization `xml:",any"`
}

type ContactInfoType struct {
	XMLName xml.Name

	PersonNm *PersonNameType `xml:"PersonNm"`

	PhoneNum *PhoneNumberType `xml:"PhoneNum"`
}

type ContactAndTaxYearInfoType struct {
	XMLName xml.Name

	TaxYr *YearType `xml:"TaxYr"`

	PersonNm *PersonNameType `xml:"PersonNm"`

	PhoneNum *PhoneNumberType `xml:"PhoneNum"`
}

// XSD SimpleType declarations

type StringType string

type Uritype string

type DateType string

type YearMonthType string

type TaxYearEndMonthDtType string

type MonthType string

type MonthDayType string

type QuarterEndDateType string

type TimestampType string

type YearType string

type BooleanType bool

type CheckboxType string

const CheckboxTypeX CheckboxType = "X"

type IntegerType int64

type IntegerNntype uint64

type IntegerPosType uint64

type LongIntegerType int64

type DecimalType float64

type DecimalNntype float64

type UsamountType int64

type UsamountNntype uint64

type UsamountNegType int64

type UsamountNonPosType int64

type UsamountPosType uint64

type UsdecimalAmountType float64

type UsdecimalAmountNntype float64

type UsdecimalAmountPosType float64

type UslargeDecimalAmountType float64

type ForeignAmountType int64

type ForeignAmountNntype uint64

type Decimal2RatioType float64

type Decimal4RatioType float64

type SmallRatioType float64

type RatioType float64

type LargeRatioType float64

type BusinessActivityCodeType int64

type RoutingTransitNumberType string

type BankAccountNumberType string

type BankAccountType string

const BankAccountType1 BankAccountType = "1"

const BankAccountType2 BankAccountType = "2"

type Ssntype string

type Eintype string

type Etintype string

type Ptintype string

type Efintype string

type Pintype string

type Isptype string

type OriginatorType string

const OriginatorTypeEro OriginatorType = "ERO"

const OriginatorTypeOnlinefiler OriginatorType = "OnlineFiler"

const OriginatorTypeReportingagent OriginatorType = "ReportingAgent"

const OriginatorTypeFinancialagent OriginatorType = "FinancialAgent"

const OriginatorTypeLargetaxpayer OriginatorType = "LargeTaxpayer"

type SignatureType string

type SoftwareIdType string

type SoftwareVersionType string

type IdType string

type IdListType string

type BusinessNameLine1Type string

type BusinessNameLine2Type string

type InCareOfNameType string

type NameLine1Type string

type PersonNameType string

type PersonTitleType string

type BusinessNameControlType string

type CheckDigitType string

type StreetAddressType string

type CityType string

type StateType string

const StateTypeAl StateType = "AL"

const StateTypeAk StateType = "AK"

const StateTypeAs StateType = "AS"

const StateTypeAz StateType = "AZ"

const StateTypeAr StateType = "AR"

const StateTypeCa StateType = "CA"

const StateTypeCo StateType = "CO"

const StateTypeMp StateType = "MP"

const StateTypeCt StateType = "CT"

const StateTypeDe StateType = "DE"

const StateTypeDc StateType = "DC"

const StateTypeFm StateType = "FM"

const StateTypeFl StateType = "FL"

const StateTypeGa StateType = "GA"

const StateTypeGu StateType = "GU"

const StateTypeHi StateType = "HI"

const StateTypeId StateType = "ID"

const StateTypeIl StateType = "IL"

const StateTypeIn StateType = "IN"

const StateTypeIa StateType = "IA"

const StateTypeKs StateType = "KS"

const StateTypeKy StateType = "KY"

const StateTypeLa StateType = "LA"

const StateTypeMe StateType = "ME"

const StateTypeMh StateType = "MH"

const StateTypeMd StateType = "MD"

const StateTypeMa StateType = "MA"

const StateTypeMi StateType = "MI"

const StateTypeMn StateType = "MN"

const StateTypeMs StateType = "MS"

const StateTypeMo StateType = "MO"

const StateTypeMt StateType = "MT"

const StateTypeNe StateType = "NE"

const StateTypeNv StateType = "NV"

const StateTypeNh StateType = "NH"

const StateTypeNj StateType = "NJ"

const StateTypeNm StateType = "NM"

const StateTypeNy StateType = "NY"

const StateTypeNc StateType = "NC"

const StateTypeNd StateType = "ND"

const StateTypeOh StateType = "OH"

const StateTypeOk StateType = "OK"

const StateTypeOr StateType = "OR"

const StateTypePw StateType = "PW"

const StateTypePa StateType = "PA"

const StateTypePr StateType = "PR"

const StateTypeRi StateType = "RI"

const StateTypeSc StateType = "SC"

const StateTypeSd StateType = "SD"

const StateTypeTn StateType = "TN"

const StateTypeTx StateType = "TX"

const StateTypeVi StateType = "VI"

const StateTypeUt StateType = "UT"

const StateTypeVt StateType = "VT"

const StateTypeVa StateType = "VA"

const StateTypeWa StateType = "WA"

const StateTypeWv StateType = "WV"

const StateTypeWi StateType = "WI"

const StateTypeWy StateType = "WY"

const StateTypeAa StateType = "AA"

const StateTypeAe StateType = "AE"

const StateTypeAp StateType = "AP"

type FutastateCdType string

const FutastateCdTypeAl FutastateCdType = "AL"

const FutastateCdTypeAk FutastateCdType = "AK"

const FutastateCdTypeAz FutastateCdType = "AZ"

const FutastateCdTypeAr FutastateCdType = "AR"

const FutastateCdTypeCa FutastateCdType = "CA"

const FutastateCdTypeCo FutastateCdType = "CO"

const FutastateCdTypeCt FutastateCdType = "CT"

const FutastateCdTypeDe FutastateCdType = "DE"

const FutastateCdTypeDc FutastateCdType = "DC"

const FutastateCdTypeFl FutastateCdType = "FL"

const FutastateCdTypeGa FutastateCdType = "GA"

const FutastateCdTypeHi FutastateCdType = "HI"

const FutastateCdTypeId FutastateCdType = "ID"

const FutastateCdTypeIl FutastateCdType = "IL"

const FutastateCdTypeIn FutastateCdType = "IN"

const FutastateCdTypeIa FutastateCdType = "IA"

const FutastateCdTypeKs FutastateCdType = "KS"

const FutastateCdTypeKy FutastateCdType = "KY"

const FutastateCdTypeLa FutastateCdType = "LA"

const FutastateCdTypeMe FutastateCdType = "ME"

const FutastateCdTypeMd FutastateCdType = "MD"

const FutastateCdTypeMa FutastateCdType = "MA"

const FutastateCdTypeMi FutastateCdType = "MI"

const FutastateCdTypeMn FutastateCdType = "MN"

const FutastateCdTypeMs FutastateCdType = "MS"

const FutastateCdTypeMo FutastateCdType = "MO"

const FutastateCdTypeMt FutastateCdType = "MT"

const FutastateCdTypeNe FutastateCdType = "NE"

const FutastateCdTypeNv FutastateCdType = "NV"

const FutastateCdTypeNh FutastateCdType = "NH"

const FutastateCdTypeNj FutastateCdType = "NJ"

const FutastateCdTypeNm FutastateCdType = "NM"

const FutastateCdTypeNy FutastateCdType = "NY"

const FutastateCdTypeNc FutastateCdType = "NC"

const FutastateCdTypeNd FutastateCdType = "ND"

const FutastateCdTypeOh FutastateCdType = "OH"

const FutastateCdTypeOk FutastateCdType = "OK"

const FutastateCdTypeOr FutastateCdType = "OR"

const FutastateCdTypePa FutastateCdType = "PA"

const FutastateCdTypePr FutastateCdType = "PR"

const FutastateCdTypeRi FutastateCdType = "RI"

const FutastateCdTypeSc FutastateCdType = "SC"

const FutastateCdTypeSd FutastateCdType = "SD"

const FutastateCdTypeTn FutastateCdType = "TN"

const FutastateCdTypeTx FutastateCdType = "TX"

const FutastateCdTypeVi FutastateCdType = "VI"

const FutastateCdTypeUt FutastateCdType = "UT"

const FutastateCdTypeVt FutastateCdType = "VT"

const FutastateCdTypeVa FutastateCdType = "VA"

const FutastateCdTypeWa FutastateCdType = "WA"

const FutastateCdTypeWv FutastateCdType = "WV"

const FutastateCdTypeWi FutastateCdType = "WI"

const FutastateCdTypeWy FutastateCdType = "WY"

type ZipcodeType string

type PhoneNumberType string

type ForeignPhoneNumberType string

type EmailAddressType string

type TextType string

type ExplanationType string

type LineExplanationType string

type ShortExplanationType string

type ShortDescriptionType string

type MediumExplanationType string

type LongExplanationType string

type CountryType string

const CountryTypeAf CountryType = "AF"

const CountryTypeAx CountryType = "AX"

const CountryTypeAl CountryType = "AL"

const CountryTypeAg CountryType = "AG"

const CountryTypeAq CountryType = "AQ"

const CountryTypeAn CountryType = "AN"

const CountryTypeAo CountryType = "AO"

const CountryTypeAv CountryType = "AV"

const CountryTypeAy CountryType = "AY"

const CountryTypeAc CountryType = "AC"

const CountryTypeAr CountryType = "AR"

const CountryTypeAm CountryType = "AM"

const CountryTypeAa CountryType = "AA"

const CountryTypeAt CountryType = "AT"

const CountryTypeAs CountryType = "AS"

const CountryTypeAu CountryType = "AU"

const CountryTypeAj CountryType = "AJ"

const CountryTypeBf CountryType = "BF"

const CountryTypeBa CountryType = "BA"

const CountryTypeFq CountryType = "FQ"

const CountryTypeBg CountryType = "BG"

const CountryTypeBb CountryType = "BB"

const CountryTypeBo CountryType = "BO"

const CountryTypeBe CountryType = "BE"

const CountryTypeBh CountryType = "BH"

const CountryTypeBn CountryType = "BN"

const CountryTypeBd CountryType = "BD"

const CountryTypeBt CountryType = "BT"

const CountryTypeBl CountryType = "BL"

const CountryTypeBk CountryType = "BK"

const CountryTypeBc CountryType = "BC"

const CountryTypeBv CountryType = "BV"

const CountryTypeBr CountryType = "BR"

const CountryTypeIo CountryType = "IO"

const CountryTypeVi CountryType = "VI"

const CountryTypeBx CountryType = "BX"

const CountryTypeBu CountryType = "BU"

const CountryTypeUv CountryType = "UV"

const CountryTypeBm CountryType = "BM"

const CountryTypeBy CountryType = "BY"

const CountryTypeCb CountryType = "CB"

const CountryTypeCm CountryType = "CM"

const CountryTypeCa CountryType = "CA"

const CountryTypeCv CountryType = "CV"

const CountryTypeCj CountryType = "CJ"

const CountryTypeCt CountryType = "CT"

const CountryTypeCd CountryType = "CD"

const CountryTypeCi CountryType = "CI"

const CountryTypeCh CountryType = "CH"

const CountryTypeKt CountryType = "KT"

const CountryTypeIp CountryType = "IP"

const CountryTypeCk CountryType = "CK"

const CountryTypeCo CountryType = "CO"

const CountryTypeCn CountryType = "CN"

const CountryTypeCf CountryType = "CF"

const CountryTypeCg CountryType = "CG"

const CountryTypeCw CountryType = "CW"

const CountryTypeCr CountryType = "CR"

const CountryTypeCs CountryType = "CS"

const CountryTypeIv CountryType = "IV"

const CountryTypeHr CountryType = "HR"

const CountryTypeCu CountryType = "CU"

const CountryTypeUc CountryType = "UC"

const CountryTypeCy CountryType = "CY"

const CountryTypeEz CountryType = "EZ"

const CountryTypeDa CountryType = "DA"

const CountryTypeDx CountryType = "DX"

const CountryTypeDj CountryType = "DJ"

const CountryTypeDo CountryType = "DO"

const CountryTypeDr CountryType = "DR"

const CountryTypeTt CountryType = "TT"

const CountryTypeEc CountryType = "EC"

const CountryTypeEg CountryType = "EG"

const CountryTypeEs CountryType = "ES"

const CountryTypeEk CountryType = "EK"

const CountryTypeEr CountryType = "ER"

const CountryTypeEn CountryType = "EN"

const CountryTypeEt CountryType = "ET"

const CountryTypeFk CountryType = "FK"

const CountryTypeFo CountryType = "FO"

const CountryTypeFm CountryType = "FM"

const CountryTypeFj CountryType = "FJ"

const CountryTypeFi CountryType = "FI"

const CountryTypeFr CountryType = "FR"

const CountryTypeFp CountryType = "FP"

const CountryTypeFs CountryType = "FS"

const CountryTypeGb CountryType = "GB"

const CountryTypeGa CountryType = "GA"

const CountryTypeGg CountryType = "GG"

const CountryTypeGm CountryType = "GM"

const CountryTypeGh CountryType = "GH"

const CountryTypeGi CountryType = "GI"

const CountryTypeGr CountryType = "GR"

const CountryTypeGl CountryType = "GL"

const CountryTypeGj CountryType = "GJ"

const CountryTypeGq CountryType = "GQ"

const CountryTypeGt CountryType = "GT"

const CountryTypeGk CountryType = "GK"

const CountryTypeGv CountryType = "GV"

const CountryTypePu CountryType = "PU"

const CountryTypeGy CountryType = "GY"

const CountryTypeHa CountryType = "HA"

const CountryTypeHm CountryType = "HM"

const CountryTypeVt CountryType = "VT"

const CountryTypeHo CountryType = "HO"

const CountryTypeHk CountryType = "HK"

const CountryTypeHq CountryType = "HQ"

const CountryTypeHu CountryType = "HU"

const CountryTypeIc CountryType = "IC"

const CountryTypeIn CountryType = "IN"

const CountryTypeId CountryType = "ID"

const CountryTypeIr CountryType = "IR"

const CountryTypeIz CountryType = "IZ"

const CountryTypeEi CountryType = "EI"

const CountryTypeIs CountryType = "IS"

const CountryTypeIt CountryType = "IT"

const CountryTypeJm CountryType = "JM"

const CountryTypeJn CountryType = "JN"

const CountryTypeJa CountryType = "JA"

const CountryTypeDq CountryType = "DQ"

const CountryTypeJe CountryType = "JE"

const CountryTypeJq CountryType = "JQ"

const CountryTypeJo CountryType = "JO"

const CountryTypeKz CountryType = "KZ"

const CountryTypeKe CountryType = "KE"

const CountryTypeKq CountryType = "KQ"

const CountryTypeKr CountryType = "KR"

const CountryTypeKn CountryType = "KN"

const CountryTypeKs CountryType = "KS"

const CountryTypeKv CountryType = "KV"

const CountryTypeKu CountryType = "KU"

const CountryTypeKg CountryType = "KG"

const CountryTypeLa CountryType = "LA"

const CountryTypeLg CountryType = "LG"

const CountryTypeLe CountryType = "LE"

const CountryTypeLt CountryType = "LT"

const CountryTypeLi CountryType = "LI"

const CountryTypeLy CountryType = "LY"

const CountryTypeLs CountryType = "LS"

const CountryTypeLh CountryType = "LH"

const CountryTypeLu CountryType = "LU"

const CountryTypeMc CountryType = "MC"

const CountryTypeMk CountryType = "MK"

const CountryTypeMa CountryType = "MA"

const CountryTypeMi CountryType = "MI"

const CountryTypeMy CountryType = "MY"

const CountryTypeMv CountryType = "MV"

const CountryTypeMl CountryType = "ML"

const CountryTypeMt CountryType = "MT"

const CountryTypeIm CountryType = "IM"

const CountryTypeRm CountryType = "RM"

const CountryTypeMr CountryType = "MR"

const CountryTypeMp CountryType = "MP"

const CountryTypeMx CountryType = "MX"

const CountryTypeMq CountryType = "MQ"

const CountryTypeMd CountryType = "MD"

const CountryTypeMn CountryType = "MN"

const CountryTypeMg CountryType = "MG"

const CountryTypeMj CountryType = "MJ"

const CountryTypeMh CountryType = "MH"

const CountryTypeMo CountryType = "MO"

const CountryTypeMz CountryType = "MZ"

const CountryTypeWa CountryType = "WA"

const CountryTypeNr CountryType = "NR"

const CountryTypeBq CountryType = "BQ"

const CountryTypeNp CountryType = "NP"

const CountryTypeNl CountryType = "NL"

const CountryTypeNc CountryType = "NC"

const CountryTypeNz CountryType = "NZ"

const CountryTypeNu CountryType = "NU"

const CountryTypeNg CountryType = "NG"

const CountryTypeNi CountryType = "NI"

const CountryTypeNe CountryType = "NE"

const CountryTypeNf CountryType = "NF"

const CountryTypeCq CountryType = "CQ"

const CountryTypeNo CountryType = "NO"

const CountryTypeMu CountryType = "MU"

const CountryTypeOc CountryType = "OC"

const CountryTypePk CountryType = "PK"

const CountryTypePs CountryType = "PS"

const CountryTypeLq CountryType = "LQ"

const CountryTypePm CountryType = "PM"

const CountryTypePp CountryType = "PP"

const CountryTypePf CountryType = "PF"

const CountryTypePa CountryType = "PA"

const CountryTypePe CountryType = "PE"

const CountryTypeRp CountryType = "RP"

const CountryTypePc CountryType = "PC"

const CountryTypePl CountryType = "PL"

const CountryTypePo CountryType = "PO"

const CountryTypeRq CountryType = "RQ"

const CountryTypeQa CountryType = "QA"

const CountryTypeRo CountryType = "RO"

const CountryTypeRs CountryType = "RS"

const CountryTypeRw CountryType = "RW"

const CountryTypeTb CountryType = "TB"

const CountryTypeRn CountryType = "RN"

const CountryTypeWs CountryType = "WS"

const CountryTypeSm CountryType = "SM"

const CountryTypeTp CountryType = "TP"

const CountryTypeSa CountryType = "SA"

const CountryTypeSg CountryType = "SG"

const CountryTypeRi CountryType = "RI"

const CountryTypeSe CountryType = "SE"

const CountryTypeSl CountryType = "SL"

const CountryTypeSn CountryType = "SN"

const CountryTypeNn CountryType = "NN"

const CountryTypeLo CountryType = "LO"

const CountryTypeSi CountryType = "SI"

const CountryTypeBp CountryType = "BP"

const CountryTypeSo CountryType = "SO"

const CountryTypeSf CountryType = "SF"

const CountryTypeSx CountryType = "SX"

const CountryTypeOd CountryType = "OD"

const CountryTypeSp CountryType = "SP"

const CountryTypePg CountryType = "PG"

const CountryTypeCe CountryType = "CE"

const CountryTypeSh CountryType = "SH"

const CountryTypeSc CountryType = "SC"

const CountryTypeSt CountryType = "ST"

const CountryTypeSb CountryType = "SB"

const CountryTypeVc CountryType = "VC"

const CountryTypeSu CountryType = "SU"

const CountryTypeNs CountryType = "NS"

const CountryTypeSv CountryType = "SV"

const CountryTypeWz CountryType = "WZ"

const CountryTypeSw CountryType = "SW"

const CountryTypeSz CountryType = "SZ"

const CountryTypeSy CountryType = "SY"

const CountryTypeTw CountryType = "TW"

const CountryTypeTi CountryType = "TI"

const CountryTypeTz CountryType = "TZ"

const CountryTypeTh CountryType = "TH"

const CountryTypeTo CountryType = "TO"

const CountryTypeTl CountryType = "TL"

const CountryTypeTn CountryType = "TN"

const CountryTypeTd CountryType = "TD"

const CountryTypeTs CountryType = "TS"

const CountryTypeTu CountryType = "TU"

const CountryTypeTx CountryType = "TX"

const CountryTypeTk CountryType = "TK"

const CountryTypeTv CountryType = "TV"

const CountryTypeUg CountryType = "UG"

const CountryTypeUp CountryType = "UP"

const CountryTypeAe CountryType = "AE"

const CountryTypeUk CountryType = "UK"

const CountryTypeUy CountryType = "UY"

const CountryTypeUz CountryType = "UZ"

const CountryTypeNh CountryType = "NH"

const CountryTypeVe CountryType = "VE"

const CountryTypeVm CountryType = "VM"

const CountryTypeVq CountryType = "VQ"

const CountryTypeWq CountryType = "WQ"

const CountryTypeWf CountryType = "WF"

const CountryTypeWi CountryType = "WI"

const CountryTypeYm CountryType = "YM"

const CountryTypeZa CountryType = "ZA"

const CountryTypeZi CountryType = "ZI"

type AllCountriesType string

type DepreciationConventionCodeType string

const DepreciationConventionCodeTypeHy DepreciationConventionCodeType = "HY"

const DepreciationConventionCodeTypeMq DepreciationConventionCodeType = "MQ"

const DepreciationConventionCodeTypeMm DepreciationConventionCodeType = "MM"

const DepreciationConventionCodeTypeSl DepreciationConventionCodeType = "S/L"

type DepreciationConventionType string

type DepreciationMethodCodeType string

const DepreciationMethodCodeType200Db DepreciationMethodCodeType = "200 DB"

const DepreciationMethodCodeType150Db DepreciationMethodCodeType = "150 DB"

const DepreciationMethodCodeTypeDb DepreciationMethodCodeType = "DB"

const DepreciationMethodCodeTypeSl DepreciationMethodCodeType = "S/L"

const DepreciationMethodCodeTypeVarious DepreciationMethodCodeType = "Various"

type DepreciationMethodType string

type Bintype string

type GtxkeyType string

type MethodOfAccountingType string

const MethodOfAccountingTypeCash MethodOfAccountingType = "cash"

const MethodOfAccountingTypeAccrual MethodOfAccountingType = "accrual"

const MethodOfAccountingTypeHybrid MethodOfAccountingType = "hybrid"

type NumericType string

type AlphaNumericType string

type AlphaNumericAndParenthesesType string

type IrsserviceCenterType string

type StringVarioustype string

const StringVarioustypeVarious StringVarioustype = "VARIOUS"

type CusipnumberType string

type FuelGallonsType int64

type FuelGallonsNntype uint64

type MilesType int64

type MilesNntype uint64

type GovernmentCodeType string

const GovernmentCodeTypeIrs GovernmentCodeType = "IRS"

const GovernmentCodeTypeAlst GovernmentCodeType = "ALST"

const GovernmentCodeTypeAkst GovernmentCodeType = "AKST"

const GovernmentCodeTypeAzst GovernmentCodeType = "AZST"

const GovernmentCodeTypeArst GovernmentCodeType = "ARST"

const GovernmentCodeTypeCast GovernmentCodeType = "CAST"

const GovernmentCodeTypeCnct GovernmentCodeType = "CNCT"

const GovernmentCodeTypeCoct GovernmentCodeType = "COCT"

const GovernmentCodeTypeCost GovernmentCodeType = "COST"

const GovernmentCodeTypeCtst GovernmentCodeType = "CTST"

const GovernmentCodeTypeDect GovernmentCodeType = "DECT"

const GovernmentCodeTypeDest GovernmentCodeType = "DEST"

const GovernmentCodeTypeDcst GovernmentCodeType = "DCST"

const GovernmentCodeTypeFlst GovernmentCodeType = "FLST"

const GovernmentCodeTypeGast GovernmentCodeType = "GAST"

const GovernmentCodeTypeHist GovernmentCodeType = "HIST"

const GovernmentCodeTypeIdst GovernmentCodeType = "IDST"

const GovernmentCodeTypeIlst GovernmentCodeType = "ILST"

const GovernmentCodeTypeInst GovernmentCodeType = "INST"

const GovernmentCodeTypeIast GovernmentCodeType = "IAST"

const GovernmentCodeTypeKact GovernmentCodeType = "KACT"

const GovernmentCodeTypeKsst GovernmentCodeType = "KSST"

const GovernmentCodeTypeKyst GovernmentCodeType = "KYST"

const GovernmentCodeTypeLast GovernmentCodeType = "LAST"

const GovernmentCodeTypeLect GovernmentCodeType = "LECT"

const GovernmentCodeTypeLxct GovernmentCodeType = "LXCT"

const GovernmentCodeTypeMest GovernmentCodeType = "MEST"

const GovernmentCodeTypeMdst GovernmentCodeType = "MDST"

const GovernmentCodeTypeMast GovernmentCodeType = "MAST"

const GovernmentCodeTypeMist GovernmentCodeType = "MIST"

const GovernmentCodeTypeMnst GovernmentCodeType = "MNST"

const GovernmentCodeTypeMsst GovernmentCodeType = "MSST"

const GovernmentCodeTypeMost GovernmentCodeType = "MOST"

const GovernmentCodeTypeMtst GovernmentCodeType = "MTST"

const GovernmentCodeTypeNest GovernmentCodeType = "NEST"

const GovernmentCodeTypeNvst GovernmentCodeType = "NVST"

const GovernmentCodeTypeNhst GovernmentCodeType = "NHST"

const GovernmentCodeTypeNjst GovernmentCodeType = "NJST"

const GovernmentCodeTypeNmst GovernmentCodeType = "NMST"

const GovernmentCodeTypeNyst GovernmentCodeType = "NYST"

const GovernmentCodeTypeNcst GovernmentCodeType = "NCST"

const GovernmentCodeTypeNdst GovernmentCodeType = "NDST"

const GovernmentCodeTypeOcct GovernmentCodeType = "OCCT"

const GovernmentCodeTypeOhst GovernmentCodeType = "OHST"

const GovernmentCodeTypeOkst GovernmentCodeType = "OKST"

const GovernmentCodeTypeOrct GovernmentCodeType = "ORCT"

const GovernmentCodeTypeOrst GovernmentCodeType = "ORST"

const GovernmentCodeTypePast GovernmentCodeType = "PAST"

const GovernmentCodeTypePoct GovernmentCodeType = "POCT"

const GovernmentCodeTypeRist GovernmentCodeType = "RIST"

const GovernmentCodeTypeScst GovernmentCodeType = "SCST"

const GovernmentCodeTypeSdst GovernmentCodeType = "SDST"

const GovernmentCodeTypeSlct GovernmentCodeType = "SLCT"

const GovernmentCodeTypeTnst GovernmentCodeType = "TNST"

const GovernmentCodeTypeToct GovernmentCodeType = "TOCT"

const GovernmentCodeTypeTxst GovernmentCodeType = "TXST"

const GovernmentCodeTypeUtst GovernmentCodeType = "UTST"

const GovernmentCodeTypeVtst GovernmentCodeType = "VTST"

const GovernmentCodeTypeVast GovernmentCodeType = "VAST"

const GovernmentCodeTypeWast GovernmentCodeType = "WAST"

const GovernmentCodeTypeWvst GovernmentCodeType = "WVST"

const GovernmentCodeTypeWist GovernmentCodeType = "WIST"

const GovernmentCodeTypeWyst GovernmentCodeType = "WYST"

const GovernmentCodeTypeNyct GovernmentCodeType = "NYCT"

const GovernmentCodeTypePhct GovernmentCodeType = "PHCT"

type TaxShelterRegistrationType string

type NumberOfSharesType int64

type Vintype string

type NumberOfDaysType int64

type PinenteredByType string

const PinenteredByTypeTaxpayer PinenteredByType = "Taxpayer"

const PinenteredByTypeEro PinenteredByType = "ERO"

type PincodeType string

const PincodeTypePractitioner PincodeType = "Practitioner"

const PincodeTypeSelfSelectPractitioner PincodeType = "Self-Select Practitioner"

const PincodeTypeSelfSelectOnLine PincodeType = "Self-Select On-Line"

type ConsortiumType string

const ConsortiumTypeEnglishFreeFile ConsortiumType = "English Free-File"

const ConsortiumTypeSpanishFreeFile ConsortiumType = "Spanish Free-File"

const ConsortiumTypeFreeFillableForms ConsortiumType = "Free Fillable Forms"

type PartnersPageFilingType string

const PartnersPageFilingTypePartnersPageEnglish PartnersPageFilingType = "Partners Page English"

const PartnersPageFilingTypePartnersPageSpanish PartnersPageFilingType = "Partners Page Spanish"

type PersonFirstNameType string

type PersonLastNameType string

type PersonNameControlType string

type Ipv4Type string

type Ipv6Type string

type TimeType string

type TimezoneType string

const TimezoneTypeUs TimezoneType = "US"

const TimezoneTypeEs TimezoneType = "ES"

const TimezoneTypeEd TimezoneType = "ED"

const TimezoneTypeCs TimezoneType = "CS"

const TimezoneTypeCd TimezoneType = "CD"

const TimezoneTypeMs TimezoneType = "MS"

const TimezoneTypeMd TimezoneType = "MD"

const TimezoneTypePs TimezoneType = "PS"

const TimezoneTypePd TimezoneType = "PD"

const TimezoneTypeAs TimezoneType = "AS"

const TimezoneTypeAd TimezoneType = "AD"

const TimezoneTypeHs TimezoneType = "HS"

const TimezoneTypeHd TimezoneType = "HD"

type Stintype string

type RegistrationNumType string

type DeviceIdType string

type ForeignRegulatedInvestmtCompCdType string

const ForeignRegulatedInvestmtCompCdTypeRic ForeignRegulatedInvestmtCompCdType = "RIC"

type SubmissionIdType string

type Ftintype string

type CurrencyCodeType string

const CurrencyCodeTypeXua CurrencyCodeType = "XUA"

const CurrencyCodeTypeAfn CurrencyCodeType = "AFN"

const CurrencyCodeTypeDzd CurrencyCodeType = "DZD"

const CurrencyCodeTypeArs CurrencyCodeType = "ARS"

const CurrencyCodeTypeAmd CurrencyCodeType = "AMD"

const CurrencyCodeTypeAwg CurrencyCodeType = "AWG"

const CurrencyCodeTypeAud CurrencyCodeType = "AUD"

const CurrencyCodeTypeAzn CurrencyCodeType = "AZN"

const CurrencyCodeTypeBsd CurrencyCodeType = "BSD"

const CurrencyCodeTypeBhd CurrencyCodeType = "BHD"

const CurrencyCodeTypeThb CurrencyCodeType = "THB"

const CurrencyCodeTypePab CurrencyCodeType = "PAB"

const CurrencyCodeTypeBbd CurrencyCodeType = "BBD"

const CurrencyCodeTypeByn CurrencyCodeType = "BYN"

const CurrencyCodeTypeBzd CurrencyCodeType = "BZD"

const CurrencyCodeTypeBmd CurrencyCodeType = "BMD"

const CurrencyCodeTypeVes CurrencyCodeType = "VES"

const CurrencyCodeTypeBob CurrencyCodeType = "BOB"

const CurrencyCodeTypeBrl CurrencyCodeType = "BRL"

const CurrencyCodeTypeBnd CurrencyCodeType = "BND"

const CurrencyCodeTypeBgn CurrencyCodeType = "BGN"

const CurrencyCodeTypeBif CurrencyCodeType = "BIF"

const CurrencyCodeTypeCve CurrencyCodeType = "CVE"

const CurrencyCodeTypeCad CurrencyCodeType = "CAD"

const CurrencyCodeTypeKyd CurrencyCodeType = "KYD"

const CurrencyCodeTypeXof CurrencyCodeType = "XOF"

const CurrencyCodeTypeXaf CurrencyCodeType = "XAF"

const CurrencyCodeTypeXpf CurrencyCodeType = "XPF"

const CurrencyCodeTypeClp CurrencyCodeType = "CLP"

const CurrencyCodeTypeCop CurrencyCodeType = "COP"

const CurrencyCodeTypeKmf CurrencyCodeType = "KMF"

const CurrencyCodeTypeCdf CurrencyCodeType = "CDF"

const CurrencyCodeTypeBam CurrencyCodeType = "BAM"

const CurrencyCodeTypeNio CurrencyCodeType = "NIO"

const CurrencyCodeTypeCrc CurrencyCodeType = "CRC"

const CurrencyCodeTypeCup CurrencyCodeType = "CUP"

const CurrencyCodeTypeCzk CurrencyCodeType = "CZK"

const CurrencyCodeTypeGmd CurrencyCodeType = "GMD"

const CurrencyCodeTypeDkk CurrencyCodeType = "DKK"

const CurrencyCodeTypeMkd CurrencyCodeType = "MKD"

const CurrencyCodeTypeDjf CurrencyCodeType = "DJF"

const CurrencyCodeTypeStn CurrencyCodeType = "STN"

const CurrencyCodeTypeDop CurrencyCodeType = "DOP"

const CurrencyCodeTypeVnd CurrencyCodeType = "VND"

const CurrencyCodeTypeXcd CurrencyCodeType = "XCD"

const CurrencyCodeTypeEgp CurrencyCodeType = "EGP"

const CurrencyCodeTypeSvc CurrencyCodeType = "SVC"

const CurrencyCodeTypeEtb CurrencyCodeType = "ETB"

const CurrencyCodeTypeEur CurrencyCodeType = "EUR"

const CurrencyCodeTypeFkp CurrencyCodeType = "FKP"

const CurrencyCodeTypeFjd CurrencyCodeType = "FJD"

const CurrencyCodeTypeHuf CurrencyCodeType = "HUF"

const CurrencyCodeTypeGhs CurrencyCodeType = "GHS"

const CurrencyCodeTypeGip CurrencyCodeType = "GIP"

const CurrencyCodeTypeHtg CurrencyCodeType = "HTG"

const CurrencyCodeTypePyg CurrencyCodeType = "PYG"

const CurrencyCodeTypeGnf CurrencyCodeType = "GNF"

const CurrencyCodeTypeGyd CurrencyCodeType = "GYD"

const CurrencyCodeTypeHkd CurrencyCodeType = "HKD"

const CurrencyCodeTypeUah CurrencyCodeType = "UAH"

const CurrencyCodeTypeIsk CurrencyCodeType = "ISK"

const CurrencyCodeTypeInr CurrencyCodeType = "INR"

const CurrencyCodeTypeIrr CurrencyCodeType = "IRR"

const CurrencyCodeTypeIqd CurrencyCodeType = "IQD"

const CurrencyCodeTypeJmd CurrencyCodeType = "JMD"

const CurrencyCodeTypeJod CurrencyCodeType = "JOD"

const CurrencyCodeTypeKes CurrencyCodeType = "KES"

const CurrencyCodeTypePgk CurrencyCodeType = "PGK"

const CurrencyCodeTypeHrk CurrencyCodeType = "HRK"

const CurrencyCodeTypeKwd CurrencyCodeType = "KWD"

const CurrencyCodeTypeAoa CurrencyCodeType = "AOA"

const CurrencyCodeTypeMmk CurrencyCodeType = "MMK"

const CurrencyCodeTypeLak CurrencyCodeType = "LAK"

const CurrencyCodeTypeGel CurrencyCodeType = "GEL"

const CurrencyCodeTypeLbp CurrencyCodeType = "LBP"

const CurrencyCodeTypeAll CurrencyCodeType = "ALL"

const CurrencyCodeTypeHnl CurrencyCodeType = "HNL"

const CurrencyCodeTypeSll CurrencyCodeType = "SLL"

const CurrencyCodeTypeLrd CurrencyCodeType = "LRD"

const CurrencyCodeTypeLyd CurrencyCodeType = "LYD"

const CurrencyCodeTypeSzl CurrencyCodeType = "SZL"

const CurrencyCodeTypeLsl CurrencyCodeType = "LSL"

const CurrencyCodeTypeMga CurrencyCodeType = "MGA"

const CurrencyCodeTypeMwk CurrencyCodeType = "MWK"

const CurrencyCodeTypeMyr CurrencyCodeType = "MYR"

const CurrencyCodeTypeMur CurrencyCodeType = "MUR"

const CurrencyCodeTypeMxn CurrencyCodeType = "MXN"

const CurrencyCodeTypeMxv CurrencyCodeType = "MXV"

const CurrencyCodeTypeMdl CurrencyCodeType = "MDL"

const CurrencyCodeTypeMad CurrencyCodeType = "MAD"

const CurrencyCodeTypeMzn CurrencyCodeType = "MZN"

const CurrencyCodeTypeBov CurrencyCodeType = "BOV"

const CurrencyCodeTypeNgn CurrencyCodeType = "NGN"

const CurrencyCodeTypeErn CurrencyCodeType = "ERN"

const CurrencyCodeTypeNad CurrencyCodeType = "NAD"

const CurrencyCodeTypeNpr CurrencyCodeType = "NPR"

const CurrencyCodeTypeAng CurrencyCodeType = "ANG"

const CurrencyCodeTypeIls CurrencyCodeType = "ILS"

const CurrencyCodeTypeTwd CurrencyCodeType = "TWD"

const CurrencyCodeTypeNzd CurrencyCodeType = "NZD"

const CurrencyCodeTypeBtn CurrencyCodeType = "BTN"

const CurrencyCodeTypeKpw CurrencyCodeType = "KPW"

const CurrencyCodeTypeNok CurrencyCodeType = "NOK"

const CurrencyCodeTypeMru CurrencyCodeType = "MRU"

const CurrencyCodeTypeTop CurrencyCodeType = "TOP"

const CurrencyCodeTypePkr CurrencyCodeType = "PKR"

const CurrencyCodeTypeMop CurrencyCodeType = "MOP"

const CurrencyCodeTypeCuc CurrencyCodeType = "CUC"

const CurrencyCodeTypeUyu CurrencyCodeType = "UYU"

const CurrencyCodeTypePhp CurrencyCodeType = "PHP"

const CurrencyCodeTypeGbp CurrencyCodeType = "GBP"

const CurrencyCodeTypeBwp CurrencyCodeType = "BWP"

const CurrencyCodeTypeQar CurrencyCodeType = "QAR"

const CurrencyCodeTypeGtq CurrencyCodeType = "GTQ"

const CurrencyCodeTypeZar CurrencyCodeType = "ZAR"

const CurrencyCodeTypeOmr CurrencyCodeType = "OMR"

const CurrencyCodeTypeKhr CurrencyCodeType = "KHR"

const CurrencyCodeTypeRon CurrencyCodeType = "RON"

const CurrencyCodeTypeMvr CurrencyCodeType = "MVR"

const CurrencyCodeTypeIdr CurrencyCodeType = "IDR"

const CurrencyCodeTypeRub CurrencyCodeType = "RUB"

const CurrencyCodeTypeRwf CurrencyCodeType = "RWF"

const CurrencyCodeTypeShp CurrencyCodeType = "SHP"

const CurrencyCodeTypeSar CurrencyCodeType = "SAR"

const CurrencyCodeTypeXdr CurrencyCodeType = "XDR"

const CurrencyCodeTypeRsd CurrencyCodeType = "RSD"

const CurrencyCodeTypeScr CurrencyCodeType = "SCR"

const CurrencyCodeTypeSgd CurrencyCodeType = "SGD"

const CurrencyCodeTypePen CurrencyCodeType = "PEN"

const CurrencyCodeTypeSbd CurrencyCodeType = "SBD"

const CurrencyCodeTypeKgs CurrencyCodeType = "KGS"

const CurrencyCodeTypeSos CurrencyCodeType = "SOS"

const CurrencyCodeTypeTjs CurrencyCodeType = "TJS"

const CurrencyCodeTypeSsp CurrencyCodeType = "SSP"

const CurrencyCodeTypeLkr CurrencyCodeType = "LKR"

const CurrencyCodeTypeXsu CurrencyCodeType = "XSU"

const CurrencyCodeTypeSdg CurrencyCodeType = "SDG"

const CurrencyCodeTypeSrd CurrencyCodeType = "SRD"

const CurrencyCodeTypeSek CurrencyCodeType = "SEK"

const CurrencyCodeTypeChf CurrencyCodeType = "CHF"

const CurrencyCodeTypeSyp CurrencyCodeType = "SYP"

const CurrencyCodeTypeBdt CurrencyCodeType = "BDT"

const CurrencyCodeTypeWst CurrencyCodeType = "WST"

const CurrencyCodeTypeTzs CurrencyCodeType = "TZS"

const CurrencyCodeTypeKzt CurrencyCodeType = "KZT"

const CurrencyCodeTypeTtd CurrencyCodeType = "TTD"

const CurrencyCodeTypeMnt CurrencyCodeType = "MNT"

const CurrencyCodeTypeTnd CurrencyCodeType = "TND"

const CurrencyCodeTypeTry CurrencyCodeType = "TRY"

const CurrencyCodeTypeTmt CurrencyCodeType = "TMT"

const CurrencyCodeTypeAed CurrencyCodeType = "AED"

const CurrencyCodeTypeUgx CurrencyCodeType = "UGX"

const CurrencyCodeTypeClf CurrencyCodeType = "CLF"

const CurrencyCodeTypeCou CurrencyCodeType = "COU"

const CurrencyCodeTypeUyw CurrencyCodeType = "UYW"

const CurrencyCodeTypeUyi CurrencyCodeType = "UYI"

const CurrencyCodeTypeUsd CurrencyCodeType = "USD"

const CurrencyCodeTypeUsn CurrencyCodeType = "USN"

const CurrencyCodeTypeUzs CurrencyCodeType = "UZS"

const CurrencyCodeTypeVuv CurrencyCodeType = "VUV"

const CurrencyCodeTypeChe CurrencyCodeType = "CHE"

const CurrencyCodeTypeChw CurrencyCodeType = "CHW"

const CurrencyCodeTypeKrw CurrencyCodeType = "KRW"

const CurrencyCodeTypeYer CurrencyCodeType = "YER"

const CurrencyCodeTypeJpy CurrencyCodeType = "JPY"

const CurrencyCodeTypeCny CurrencyCodeType = "CNY"

const CurrencyCodeTypeZmw CurrencyCodeType = "ZMW"

const CurrencyCodeTypeZwl CurrencyCodeType = "ZWL"

const CurrencyCodeTypePln CurrencyCodeType = "PLN"

type PtepgroupCodeType string

const PtepgroupCodeTypeR965A PtepgroupCodeType = "R965a"

const PtepgroupCodeTypeR965B PtepgroupCodeType = "R965b"

const PtepgroupCodeType959C1 PtepgroupCodeType = "959c1"

const PtepgroupCodeTypeR951A PtepgroupCodeType = "R951A"

const PtepgroupCodeTypeR245Ad PtepgroupCodeType = "R245Ad"

const PtepgroupCodeType965A PtepgroupCodeType = "965a"

const PtepgroupCodeType965B PtepgroupCodeType = "965b"

const PtepgroupCodeType951A PtepgroupCodeType = "951A"

const PtepgroupCodeType245Ad PtepgroupCodeType = "245Ad"

const PtepgroupCodeType951A1A PtepgroupCodeType = "951a1A"

type StockDescriptionType string

type Decimal1RatioType float64

type Decimal3RatioType float64

type AlphaRowIdType string

type RomanRowIdType string

type NumericRowIdType uint64

type AartrackingNumberType string

type FacilityIrsissdRegistrationNumType string

type LatitudeCoordinateType float64

type LongitudeCoordinateType float64

type NpsprojectNumType string

type AlphaNumericAndSpaceType string

type CheckOrNatype string

const CheckOrNatypeX CheckOrNatype = "X"

const CheckOrNatypeNa CheckOrNatype = "NA"
